### ISSUE TITLE
After t2csp, shouldn't we hide sync sets in parallel?

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/ccs2csp#1]
@enggerard  @vkoutav We now have
```
ccs   : a | a-bar
t2csp : (a_1 [] a_1_2) |a_1_2| (a_2 [] a_1_2)
```

But a CCS communication is a tau, so shouldn't the last line above be
```
t2csp : (a_1 [] a_1_2) |a_1_2| (a_2 [] a_1_2) / {a_1_2}
```
?

**Comment by enggerard** [comment]
t2csp = CCSTau-to-CSP. To achieve CCS-to-CSP = c2csp, you must indeed hide "every" tau[a | bar-a] from CCSTau, which is equivalent to hiding "every" a_ij from the t2csp translation. In short:
`c2csp(P) = t2csp(P) \ {a_ij}` 
Equivalently, you can define CCS processes within CCSTau by systematically hiding tau[a | bar-a]  actions in a parallel composition:
`P |ccs Q = (P |ccstau Q) \ {tau[a | bar-a] | a \in A(P), bar-a \in A(Q)                 (CCStoCSPgstar_v2, E.g.3.1., p12)`
(where |ccs = | and |ccstau = |_T).
Then, we have:
`t2csp(P |ccs Q) = t2csp(P |ccstau Q) \ {a_ij}`
That's why I removed explicit mention of `c2csp` in  report CCStoCSPgstar_v2.

**Comment by andrewbutterfield** [comment]
Noted - on my to-do list...
